# Generated by Django 5.1.5 on 2025-02-05 15:46

import labour_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=labour_service.models.upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
